"""Crear tablas para ciclos y prorrateos

Revision ID: ce32e4cb7861
Revises: 
Create Date: 2025-05-30 16:49:54.046511

"""
from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import mysql # No se está usando mysql.specific_type en este script

# revision identifiers, used by Alembic.
revision = 'ce32e4cb7861'
down_revision = None # Esta es tu primera migración, así que no hay revisión anterior
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - CORREGIDO ###
    op.create_table('ciclo_reglas_prorrateo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ciclo_base_code', sa.String(length=10), nullable=False),
        sa.Column('logica_descripcion', sa.String(length=255), nullable=False),
        sa.Column('mensaje_guia', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ciclo_base_code')
    )
    op.create_table('ciclos_disponibles_prorrateo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dia', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('dia')
    )
    op.create_table('planes_prorrateo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('prorrateo_dia_base', sa.Numeric(precision=10, scale=4), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre')
    )
    op.create_table('contratos_prorrateo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_cliente', sa.String(length=200), nullable=False),
        sa.Column('tipo_documento', sa.String(length=50), nullable=True),
        sa.Column('numero_documento', sa.String(length=50), nullable=True),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.Column('ciclo_base_seleccionado', sa.String(length=10), nullable=False),
        sa.Column('ciclo_final_dia', sa.Integer(), nullable=False),
        sa.Column('prorrateo_dia_aplicado', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('fecha_cierre_calculada', sa.Date(), nullable=True),
        sa.Column('prorrateo_total_calculado', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('fecha_activacion_calculada', sa.Date(), nullable=True),
        sa.Column('fecha_pago_calculada', sa.Date(), nullable=True),
        sa.Column('fecha_formulario_hoy', sa.Date(), nullable=True),
        # Para MySQL, server_default=sa.text('CURRENT_TIMESTAMP') es más estándar que sa.text('now()')
        # Aunque 'now()' usualmente funciona en MySQL. Alembic lo generó, así que lo mantenemos por ahora.
        sa.Column('fecha_registro_sistema', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['planes_prorrateo.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - CORREGIDO ###
    # El orden de drop_table debe ser el inverso de create_table,
    # y tener cuidado con las foreign keys.
    # En este caso, 'contratos_prorrateo' depende de 'planes_prorrateo'.
    op.drop_table('contratos_prorrateo')
    op.drop_table('planes_prorrateo')
    op.drop_table('ciclos_disponibles_prorrateo')
    op.drop_table('ciclo_reglas_prorrateo')
    # ### end Alembic commands ###